version: "3.3"

services:
  generation-api:
    container_name: generation-api
    image: generation-api
    hostname: generation-api
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "8080:8080"
    restart: "always"
    command: yarn start